Add va to insurance types
Gary-Community-Ventures/benefits-api pull request #290
Opened 2024-02-27 22:41 UTC by myang1010

What (if any) features are you implementing?
- Updated cfhc value, if VA selected, return 0
- Removed "dont_know" from insurance_type as we will not use "dont_know" anymore

Is there anything that you need from your teammate?
- "dont_know" is left in `Insurance` model. We may need to remove them in the future?

Please let me know if anything need to be changed. Thanks!

2024-02-27 23:17 UTC, CalebPena requested changes
Change the default of the `dont_know` field to `null` or `False` and change the default of `none` to `True`.

Could you also test that VA is saving. The easiest way to do this is to select VA for one of the household members and then go to the next member (saving the screen) and then go back, refresh the page, and make sure that it is still selected.

2024-02-27 23:17 UTC, CalebPena commented on programs/programs/connect_for_health/calculator.py
> +        if not self.screen.has_insurance_types(('va', 'private')):
I think that this would be better to add as a condition on the eligibility method.

2024-02-27 23:17 UTC, CalebPena commented on screener/models.py
> +    va = models.BooleanField(default=False)
Could you add this to the serializer as well.

2024-02-29 00:25 UTC, myang1010 commented
I think it makes sense to check "va" insurance status on household members. This "chfc" benefit should still be available for someone in the household doesn't have "va" insurance.

2024-02-29 21:25 UTC, CalebPena approved these changes
Looks good.

2024-02-29 21:26 UTC, merged