Refactor/config
Gary-Community-Ventures/benefits-api pull request #375
Opened 2024-05-22 13:41 UTC by mexi-cano

What (if anything) did you refactor?
- Updated config model and serialization to maintain object order. Updated init config data to correct order.

2024-05-23 19:59 UTC, CalebPena commented
I think that you need to run `python manage.py makemigrations` and than migrate.

2024-05-28 11:56 UTC, mexi-cano commented
Using an `OrderedDict` to return the data field as an OrderedDict instance did not work for me. I tried returning the ordered data as such but the approach did not work.

```
def ordered_data(self):
        return json.loads(json.dumps(self.data), object_pairs_hook=OrderedDict)
```

Instead I created a custom OrderedJSONField that inherits from JSONField and overrides the serialization and deserialization methods to handle ordered dictionaries. To achieve this, I made changes to the model, serializer, and created a custom field class:

Custom OrderedJSONField (fields.py):

I created a custom OrderedJSONField class that inherits from Django's `JSONField`.
In the `from_db_value` and `to_python methods`, I use `json.loads` with a `custom object_pairs_hook` that converts the deserialized JSON object into an `OrderedDict`. This ensures that the order of the keys is preserved when retrieving data from the database.
The `get_prep_value` method is used to serialize the JSON data before saving it to the database.


Model (models.py):

In the model definition, I replaced the default `JSONField` with our custom `OrderedJSONField` for the data field.
This ensures that the JSON data stored in the data field will maintain the order of the keys.


Serializer (serializers.py):

In the serializer, I specified the data field as an instance of `OrderedJSONField`.
This ensures that the serializer uses the custom field for serialization and deserialization of the JSON data.

@CalebPena

2024-05-28 17:33 UTC, CalebPena requested changes
Looks good, but you forgot to run `python manage.py makemigrations`.

2024-05-29 17:59 UTC, CalebPena approved these changes

2024-06-04 18:35 UTC, CalebPena commented
@mexi-cano Could you fix the merge conflicts?

2024-06-05 16:57 UTC, CalebPena requested changes

2024-06-05 16:57 UTC, CalebPena commented on configuration/management/commands/add_config.py
> +    category_benefits = {"cash":{"benefits":{"tanf":{"_label":"cashAssistanceBenefits.tanf","_default_message":"Cash assistance and work support (Temporary Assistance for Needy Families (TANF/Colorad
Just realized that the `category_name` needs to be a formatted message.

2024-06-11 17:45 UTC, CalebPena approved these changes

2024-06-11 17:45 UTC, merged