Fix/Add Missing Labels on the NC Specific Instance
Gary-Community-Ventures/benefits-api pull request #438
Opened 2024-07-12 16:29 UTC by msrezaie

What (if any) features are you implementing?
- Added a new directory within the Translations app meant to store any and all translation label JSON files.
  - Currently the only JSON file within this directory is the one which includes the 37 missing labels on the NC specific instance of the screener.
- The `bulk_import` command script modifies the already saved translation labels before making the import from the passed JSON file. This is not ideal when it is needed to only add/append a few translation labels as is. Added this new command script called `bulk_add_translations` which simply adds the translation labels through the JSON file on top of the already saved ones.

Any other comments, questions, or concerns?
- Use the following command to bulk add all of the missing labels using the new command script:
```
python manage.py bulk_add_translations *path to file*\37_NC_specific.json
```

2024-07-15 22:13 UTC, CalebPena requested changes

2024-07-15 22:13 UTC, CalebPena commented on translations/management/commands/bulk_add_translations.py
> +        )
```suggestion
        parser.add_argument(
            "data",
            nargs="?",
            type=argparse.FileType("r", encoding="utf-8"),
            default=stdin,
        )
```

This lets you take the file output from the stdin if you want. For example, you can run:
`test.json | python manage.py bulk_add_translations`

Also if you do it like this, than you do not need to have 37_NC_specific.json as part of the repository.

2024-07-15 22:13 UTC, CalebPena commented on translations/management/commands/bulk_add_translations.py
> +            translation = Translation.objects.add_translation(
What happens if the label already exists?

2024-07-15 22:13 UTC, CalebPena commented on translations/labels/37_NC_specific.json
We don't need to have this in the repo if you adjust the script to be able to read from stdin.

2024-07-17 16:32 UTC, msrezaie commented on translations/management/commands/bulk_add_translations.py
> +            translation = Translation.objects.add_translation(
If a label already exists, the one coming from the json will replace it. From the testing that I've done, duplicate entries doesn't happen. I believe this is handled by the add_translation method.

2024-07-17 19:26 UTC, CalebPena approved these changes
Looks good!

2024-07-17 19:26 UTC, merged